'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Activity, ShieldCheck, HeartHandshake, Award } from 'lucide-react'

export function CrisisImpact3D() {
  const [supplierUnits, setSupplierUnits] = useState(5000)

  // Dynamic calculations
  const estimatedSavingsInr = (supplierUnits * 240).toLocaleString()
  const patientsProvidedTreatment = (supplierUnits * 2.5).toLocaleString()
  const medicalWastePreventedKg = (supplierUnits * 0.08).toFixed(1)

  return (
    <section className="py-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <div className="bg-slate-900 text-white rounded-3xl p-8 sm:p-14 border border-slate-800 shadow-2xl space-y-10">
        {/* Header */}
        <div className="flex flex-col md:flex-row justify-between md:items-end gap-6 border-b border-slate-800 pb-8">
          <div className="space-y-3 max-w-2xl">
            <span className="inline-block px-3.5 py-1 rounded-full bg-teal-950 border border-teal-800 text-teal-400 text-xs font-mono font-bold uppercase tracking-wider">
              Quantifiable Impact Calculator
            </span>
            <h2 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
              Measuring Healthcare Value Restored
            </h2>
            <p className="text-sm text-slate-400 leading-relaxed">
              Estimate the direct medical expense savings and patient treatment coverage generated by your organization listing surplus stock on DawaiSetu.
            </p>
          </div>

          <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-950 px-4 py-2 rounded-2xl border border-slate-800">
            <ShieldCheck className="h-4 w-4 text-emerald-400 shrink-0" />
            <span>Audited Redistribution Formulas</span>
          </div>
        </div>

        {/* Interactive Slider Section */}
        <div className="space-y-4 max-w-3xl">
          <div className="flex justify-between items-center text-sm font-semibold">
            <label htmlFor="units-slider" className="text-slate-300">Monthly Surplus Medicine Volume (Units):</label>
            <span className="text-teal-400 font-mono text-lg font-bold">{supplierUnits.toLocaleString()} Units / Month</span>
          </div>
          <input
            id="units-slider"
            type="range"
            min="500"
            max="50000"
            step="500"
            value={supplierUnits}
            onChange={(e) => setSupplierUnits(Number(e.target.value))}
            className="w-full h-2 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-500"
          />
          <div className="flex justify-between text-[11px] text-slate-500 font-mono">
            <span>500 Units (Local Pharmacy)</span>
            <span>25,000 Units (Regional Chain)</span>
            <span>50,000 Units (Pharma Distributor)</span>
          </div>
        </div>

        {/* Dynamic Metric Display Cards */}
        <div className="grid sm:grid-cols-3 gap-6 pt-4">
          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
            <span className="text-xs text-slate-400 font-semibold uppercase tracking-wider block">Estimated Value Restored</span>
            <p className="text-3xl font-extrabold text-white font-mono">₹{estimatedSavingsInr}</p>
            <p className="text-xs text-teal-400 font-medium">Direct medical cost savings per month</p>
          </div>

          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
            <span className="text-xs text-slate-400 font-semibold uppercase tracking-wider block">Patients Provided Free Care</span>
            <p className="text-3xl font-extrabold text-white font-mono">{patientsProvidedTreatment}</p>
            <p className="text-xs text-emerald-400 font-medium">Underprivileged treatments covered</p>
          </div>

          <div className="p-6 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
            <span className="text-xs text-slate-400 font-semibold uppercase tracking-wider block">Pharmaceutical Waste Avoided</span>
            <p className="text-3xl font-extrabold text-white font-mono">{medicalWastePreventedKg} kg</p>
            <p className="text-xs text-cyan-400 font-medium">Toxic landfill incineration prevented</p>
          </div>
        </div>
      </div>
    </section>
  )
}
